spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/RoomMate?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    hikari:
      username: root
      password: '*sumin!0103'

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDB103Dialect

logging:
  level:
    org.hibernate.sql: debug #log level
    org.hibernate.type: trace #parameter value